training:
  batch_size: 4
  learning_rate: 0.0002
  epochs: 100
  log_interval: 10
  save_interval: 10
  display_intermediate_output: false
  generate_meshes: false
  sample_novel_views: false
  gpu_id: 1

data:
  image_size: 400
  train_image_paths: ['path/to/train/image1.jpg', 'path/to/train/image2.jpg', ...]
  save_dir: './model_checkpoints'